Feat calypso op
deepmodeling/dpgen2 pull request #188
Opened 2024-02-04 09:57 UTC by wangzyphysics

2024-02-04 10:21 UTC, wangzyphysics commented
4 calypso related ops have been added:
- `prep_caly_input.py`: prep the input file of calypso according to the given List[List[dict]].
- `collect_run_caly.py`: make calypso run to generate structures depend on `input.dat` in the beginning, and other steps run depend on `input.dat`, `results/`, `step`, `POSCAR_*`, `OUTCAR_*` and `CONTCAR_*`.
- `prep_run_dp_optim.py`: make structure optimization with dp.
- `run_caly_model_devi.py`: make model deviation calculation of selected trajectory frames.

And 4 ops compose 2 superpos：
The superop `caly_evo_step.py` consists of the second and third op.
The super op `prep_run_calypso.py` consists of the first op, the super `caly_evo_step.py` and the forth op.

2024-02-19 03:11 UTC, zjgemi commented on dpgen2/op/prep_caly_input.py
> +                "caly_task_grp": BigParameter(Path),  # calypso input params
Make sure the type is Path?

2024-02-19 03:37 UTC, wanghan-iapcm requested changes
- the exploration/task module needs rearrangement, i will take care in a separate PR. 
- please provide an example for the calypso exploration.

2024-02-19 03:37 UTC, wanghan-iapcm commented on dpgen2/entrypoint/submit.py
> +            # jconf = normalize_task_group_config(jj)
why skip normalizing the configuration?

2024-02-19 03:37 UTC, wanghan-iapcm commented on dpgen2/superop/block.py
> +        #     pass
remove?

2024-02-19 03:37 UTC, wanghan-iapcm commented on dpgen2/superop/block.py
> +    if block_steps.explore_style == "lmp":
I guess the two branches may be merged.  we may change the original lmp_config->expl_config and lmp_task_grp -> expl_task_grp. 
you may need to add a dummy type_map  parameter to prep_run_lmp

2024-02-21 01:18 UTC, wanghan-iapcm reviewed
please fix the pyright check.

2024-02-21 01:18 UTC, wanghan-iapcm commented on dpgen2/superop/prep_run_lmp.py
> +            "type_map": InputParameter(value=""),
default value being `[]`?

2024-02-21 08:20 UTC, wanghan-iapcm approved these changes

2024-02-22 00:33 UTC, merged